using Assets.Modules.Core;
using System.Collections.Generic;
using UnityEngine;

namespace Assets.Modules.ParallelCoordinates
{
    /// <summary>
    /// Collects line segments generated by line generator which belong to the same data index, for easier operations on all segments
    /// </summary>
    public class ContinualLine
    {
        private int _dataIndex = -1;
        private List<LineSegment> _lineSegments = new List<LineSegment>();

        private Color _color;

        public ContinualLine(int dataIndex)
        {
            _dataIndex = dataIndex;
            _color = Theme.GetColor(dataIndex);
        }

        public void AddSegment(LineSegment segment)
        {
            _lineSegments.Add(segment);
            segment.SetColor(_color);
        }

        public void RemoveSegment(LineSegment segment)
        {
            _lineSegments.Remove(segment);
        }
    }
}
